namespace GMS.Application.DTOs;

public record DeceasedListDto(
    long DeceasedId,
    string DeceasedCode,
    string FullName,
    string? FullNameBn,
    string? GenderCode,
    DateOnly? DateOfBirth,
    DateOnly DateOfDeath,
    string? Occupation,
    string RecordStatusCode,
    bool IsVerified,
    bool IsActive
);

public record DeceasedDetailDto(
    long DeceasedId,
    long GraveyardId,
    string DeceasedCode,
    string? FirstName,
    string? MiddleName,
    string? LastName,
    string FullName,
    string? FullNameBn,
    string? GenderCode,
    DateOnly? DateOfBirth,
    short? ApproximateBirthYear,
    DateOnly DateOfDeath,
    TimeOnly? DeathTime,
    string? PlaceOfBirth,
    string? PlaceOfDeath,
    string? Nationality,
    string? Occupation,
    string? ReligionCode,
    string? MaritalStatusCode,
    string? FatherName,
    string? MotherName,
    string? SpouseName,
    string? AddressLine1,
    string? City,
    string? District,
    string? Country,
    decimal? AgeAtDeathYears,
    string? DeathCause,
    string? DeathCertificateNo,
    string? PrimaryPhotoPath,
    string? ShortIntroduction,
    string RecordStatusCode,
    string VisibilityCode,
    bool IsVerified,
    bool IsActive,
    DateTime CreatedAt
);

public record CreateDeceasedDto(
    long GraveyardId,
    string DeceasedCode,
    string? FirstName,
    string? MiddleName,
    string? LastName,
    string FullName,
    string? FullNameBn,
    string? GenderCode,
    DateOnly? DateOfBirth,
    short? ApproximateBirthYear,
    DateOnly DateOfDeath,
    TimeOnly? DeathTime,
    string? PlaceOfBirth,
    string? PlaceOfDeath,
    string? Nationality,
    string? Occupation,
    string? ReligionCode,
    string? MaritalStatusCode,
    string? FatherName,
    string? MotherName,
    string? SpouseName,
    string? AddressLine1,
    string? City,
    string? District,
    string? Country,
    decimal? AgeAtDeathYears,
    string? DeathCause,
    string? DeathCertificateNo,
    string? ShortIntroduction,
    string? VisibilityCode
);

public record UpdateDeceasedDto(
    string? FirstName,
    string? MiddleName,
    string? LastName,
    string FullName,
    string? FullNameBn,
    string? GenderCode,
    DateOnly? DateOfBirth,
    DateOnly DateOfDeath,
    TimeOnly? DeathTime,
    string? PlaceOfDeath,
    string? Nationality,
    string? Occupation,
    string? ReligionCode,
    string? MaritalStatusCode,
    string? FatherName,
    string? MotherName,
    string? SpouseName,
    string? AddressLine1,
    string? City,
    string? District,
    decimal? AgeAtDeathYears,
    string? DeathCause,
    string? DeathCertificateNo,
    string? ShortIntroduction,
    string? VisibilityCode,
    string RecordStatusCode,
    bool IsActive
);
